"""add_venta_envios_table

Revision ID: 13a81d111ca1
Revises: f3a4b5c6d7e8
Create Date: 2026-03-05 21:26:41.066090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13a81d111ca1'
down_revision: Union[str, None] = 'f3a4b5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venta_envios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venta_id', sa.UUID(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('destinatario', sa.String(length=200), nullable=False),
    sa.Column('enviado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("canal IN ('whatsapp', 'email')", name='check_venta_envio_canal_valido'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_venta_envios_tenant_venta', 'venta_envios', ['tenant_id', 'venta_id'], unique=False)
    op.create_index(op.f('ix_venta_envios_tenant_id'), 'venta_envios', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_calificaciones_tenant_deleted'), table_name='calificaciones')
    op.create_index(op.f('ix_calificaciones_deleted_at'), 'calificaciones', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_calificaciones_tenant_id'), 'calificaciones', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_calificaciones_usuario_id'), 'calificaciones', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_costos_indirectos_deleted_at'), 'costos_indirectos', ['deleted_at'], unique=False)
    op.drop_index(op.f('idx_equiv_tenant_producto'), table_name='producto_equivalencias_unidad')
    op.create_index(op.f('ix_producto_equivalencias_unidad_producto_id'), 'producto_equivalencias_unidad', ['producto_id'], unique=False)
    op.create_index(op.f('ix_producto_equivalencias_unidad_tenant_id'), 'producto_equivalencias_unidad', ['tenant_id'], unique=False)
    op.alter_column('receta_costos_historicos', 'snapshot_detalle',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_receta_costos_historicos_receta_id'), 'receta_costos_historicos', ['receta_id'], unique=False)
    op.create_index(op.f('ix_receta_costos_historicos_tenant_id'), 'receta_costos_historicos', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_recetas_tenant_nombre'), table_name='recetas')
    op.create_index('idx_recetas_tenant_nombre_active', 'recetas', ['tenant_id', 'nombre'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_socia_progress_deleted_at'), 'socia_progress', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_socia_progress_deleted_at'), table_name='socia_progress')
    op.drop_index('idx_recetas_tenant_nombre_active', table_name='recetas', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('idx_recetas_tenant_nombre'), 'recetas', ['tenant_id', 'nombre'], unique=True)
    op.drop_index(op.f('ix_receta_costos_historicos_tenant_id'), table_name='receta_costos_historicos')
    op.drop_index(op.f('ix_receta_costos_historicos_receta_id'), table_name='receta_costos_historicos')
    op.alter_column('receta_costos_historicos', 'snapshot_detalle',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_producto_equivalencias_unidad_tenant_id'), table_name='producto_equivalencias_unidad')
    op.drop_index(op.f('ix_producto_equivalencias_unidad_producto_id'), table_name='producto_equivalencias_unidad')
    op.create_index(op.f('idx_equiv_tenant_producto'), 'producto_equivalencias_unidad', ['tenant_id', 'producto_id'], unique=False)
    op.drop_index(op.f('ix_costos_indirectos_deleted_at'), table_name='costos_indirectos')
    op.drop_index(op.f('ix_calificaciones_usuario_id'), table_name='calificaciones')
    op.drop_index(op.f('ix_calificaciones_tenant_id'), table_name='calificaciones')
    op.drop_index(op.f('ix_calificaciones_deleted_at'), table_name='calificaciones')
    op.create_index(op.f('idx_calificaciones_tenant_deleted'), 'calificaciones', ['tenant_id', 'deleted_at'], unique=False)
    op.drop_index(op.f('ix_venta_envios_tenant_id'), table_name='venta_envios')
    op.drop_index('idx_venta_envios_tenant_venta', table_name='venta_envios')
    op.drop_table('venta_envios')
    # ### end Alembic commands ###
