"""p0_contabilidad_fundamentos

Revision ID: 23fa462778a8
Revises: 470bb2b033d8
Create Date: 2026-02-14 12:06:46.952340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '23fa462778a8'
down_revision: Union[str, None] = '470bb2b033d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodos_contables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('cerrado_por', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("estado IN ('ABIERTO', 'CERRADO_PARCIAL', 'CERRADO')", name='ck_periodos_estado_valid'),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='ck_periodos_mes_valid'),
    sa.ForeignKeyConstraint(['cerrado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'anio', 'mes', name='uq_periodos_tenant_anio_mes')
    )
    op.create_index(op.f('ix_periodos_contables_tenant_id'), 'periodos_contables', ['tenant_id'], unique=False)
    op.add_column('asientos_contables', sa.Column('periodo_id', sa.UUID(), nullable=True))
    op.add_column('asientos_contables', sa.Column('tercero_id', sa.UUID(), nullable=True))
    op.create_index('idx_asientos_periodo', 'asientos_contables', ['periodo_id'], unique=False)
    op.create_index('idx_asientos_tenant_tercero', 'asientos_contables', ['tenant_id', 'tercero_id'], unique=False)
    op.create_foreign_key('fk_asientos_tercero', 'asientos_contables', 'terceros', ['tercero_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_asientos_periodo', 'asientos_contables', 'periodos_contables', ['periodo_id'], ['id'], ondelete='RESTRICT')

    # Data migration: create ABIERTO periods for existing asientos and assign periodo_id
    conn = op.get_bind()
    conn.execute(text("""
        INSERT INTO periodos_contables (id, tenant_id, anio, mes, estado, created_at, updated_at)
        SELECT gen_random_uuid(), sub.tid, sub.anio, sub.mes, 'ABIERTO', now(), now()
        FROM (
            SELECT DISTINCT a.tenant_id AS tid,
                   EXTRACT(YEAR FROM a.fecha)::int AS anio,
                   EXTRACT(MONTH FROM a.fecha)::int AS mes
            FROM asientos_contables a
        ) sub
        WHERE NOT EXISTS (
            SELECT 1 FROM periodos_contables p
            WHERE p.tenant_id = sub.tid
              AND p.anio = sub.anio
              AND p.mes = sub.mes
        )
    """))
    conn.execute(text("""
        UPDATE asientos_contables a
        SET periodo_id = p.id
        FROM periodos_contables p
        WHERE p.tenant_id = a.tenant_id
          AND p.anio = EXTRACT(YEAR FROM a.fecha)::int
          AND p.mes = EXTRACT(MONTH FROM a.fecha)::int
          AND a.periodo_id IS NULL
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_asientos_periodo', 'asientos_contables', type_='foreignkey')
    op.drop_constraint('fk_asientos_tercero', 'asientos_contables', type_='foreignkey')
    op.drop_index('idx_asientos_tenant_tercero', table_name='asientos_contables')
    op.drop_index('idx_asientos_periodo', table_name='asientos_contables')
    op.drop_column('asientos_contables', 'tercero_id')
    op.drop_column('asientos_contables', 'periodo_id')
    op.drop_index(op.f('ix_periodos_contables_tenant_id'), table_name='periodos_contables')
    op.drop_table('periodos_contables')
    # ### end Alembic commands ###
