"""add_url_pdf_to_ventas_and_cotizaciones

Revision ID: 27e3081a2522
Revises: ff850d4bb783
Create Date: 2026-02-12 11:30:16.137304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e3081a2522'
down_revision: Union[str, None] = 'ff850d4bb783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones', sa.Column('url_pdf', sa.String(length=500), nullable=True))
    op.add_column('ventas', sa.Column('url_pdf', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'url_pdf')
    op.drop_column('cotizaciones', 'url_pdf')
    # ### end Alembic commands ###
