"""add_audit_columns_to_movimientos_inventario

Revision ID: 470bb2b033d8
Revises: a791fb678a02
Create Date: 2026-02-13 23:39:12.668851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470bb2b033d8'
down_revision: Union[str, None] = 'a791fb678a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asientos_contables', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('asientos_contables', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_asientos_contables_created_by'), table_name='asientos_contables')
    op.drop_index(op.f('ix_asientos_contables_updated_by'), table_name='asientos_contables')
    op.create_index(op.f('ix_asientos_contables_deleted_at'), 'asientos_contables', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'asientos_contables', 'usuarios', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_compras_created_by'), table_name='compras')
    op.drop_index(op.f('ix_compras_updated_by'), table_name='compras')
    op.drop_index(op.f('ix_cotizaciones_created_by'), table_name='cotizaciones')
    op.drop_index(op.f('ix_cotizaciones_updated_by'), table_name='cotizaciones')
    op.drop_index(op.f('ix_crm_activities_created_by'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_updated_by'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_deals_created_by'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_updated_by'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_pipelines_created_by'), table_name='crm_pipelines')
    op.drop_index(op.f('ix_crm_pipelines_updated_by'), table_name='crm_pipelines')
    op.drop_index(op.f('ix_crm_stages_created_by'), table_name='crm_stages')
    op.drop_index(op.f('ix_crm_stages_updated_by'), table_name='crm_stages')
    op.add_column('movimientos_inventario', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('movimientos_inventario', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('movimientos_inventario', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_movimientos_inventario_created_by'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_updated_by'), table_name='movimientos_inventario')
    op.create_index(op.f('ix_movimientos_inventario_deleted_at'), 'movimientos_inventario', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'movimientos_inventario', 'usuarios', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_ordenes_produccion_created_by'), table_name='ordenes_produccion')
    op.drop_index(op.f('ix_ordenes_produccion_updated_by'), table_name='ordenes_produccion')
    op.drop_index(op.f('ix_productos_created_by'), table_name='productos')
    op.drop_index(op.f('ix_productos_updated_by'), table_name='productos')
    op.drop_index(op.f('ix_recetas_created_by'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_updated_by'), table_name='recetas')
    op.drop_index(op.f('ix_terceros_created_by'), table_name='terceros')
    op.drop_index(op.f('ix_terceros_updated_by'), table_name='terceros')
    op.drop_index(op.f('ix_ventas_created_by'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_updated_by'), table_name='ventas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ventas_updated_by'), 'ventas', ['updated_by'], unique=False)
    op.create_index(op.f('ix_ventas_created_by'), 'ventas', ['created_by'], unique=False)
    op.create_index(op.f('ix_terceros_updated_by'), 'terceros', ['updated_by'], unique=False)
    op.create_index(op.f('ix_terceros_created_by'), 'terceros', ['created_by'], unique=False)
    op.create_index(op.f('ix_recetas_updated_by'), 'recetas', ['updated_by'], unique=False)
    op.create_index(op.f('ix_recetas_created_by'), 'recetas', ['created_by'], unique=False)
    op.create_index(op.f('ix_productos_updated_by'), 'productos', ['updated_by'], unique=False)
    op.create_index(op.f('ix_productos_created_by'), 'productos', ['created_by'], unique=False)
    op.create_index(op.f('ix_ordenes_produccion_updated_by'), 'ordenes_produccion', ['updated_by'], unique=False)
    op.create_index(op.f('ix_ordenes_produccion_created_by'), 'ordenes_produccion', ['created_by'], unique=False)
    op.drop_constraint(None, 'movimientos_inventario', type_='foreignkey')
    op.drop_index(op.f('ix_movimientos_inventario_deleted_at'), table_name='movimientos_inventario')
    op.create_index(op.f('ix_movimientos_inventario_updated_by'), 'movimientos_inventario', ['updated_by'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_created_by'), 'movimientos_inventario', ['created_by'], unique=False)
    op.drop_column('movimientos_inventario', 'updated_at')
    op.drop_column('movimientos_inventario', 'deleted_by')
    op.drop_column('movimientos_inventario', 'deleted_at')
    op.create_index(op.f('ix_crm_stages_updated_by'), 'crm_stages', ['updated_by'], unique=False)
    op.create_index(op.f('ix_crm_stages_created_by'), 'crm_stages', ['created_by'], unique=False)
    op.create_index(op.f('ix_crm_pipelines_updated_by'), 'crm_pipelines', ['updated_by'], unique=False)
    op.create_index(op.f('ix_crm_pipelines_created_by'), 'crm_pipelines', ['created_by'], unique=False)
    op.create_index(op.f('ix_crm_deals_updated_by'), 'crm_deals', ['updated_by'], unique=False)
    op.create_index(op.f('ix_crm_deals_created_by'), 'crm_deals', ['created_by'], unique=False)
    op.create_index(op.f('ix_crm_activities_updated_by'), 'crm_activities', ['updated_by'], unique=False)
    op.create_index(op.f('ix_crm_activities_created_by'), 'crm_activities', ['created_by'], unique=False)
    op.create_index(op.f('ix_cotizaciones_updated_by'), 'cotizaciones', ['updated_by'], unique=False)
    op.create_index(op.f('ix_cotizaciones_created_by'), 'cotizaciones', ['created_by'], unique=False)
    op.create_index(op.f('ix_compras_updated_by'), 'compras', ['updated_by'], unique=False)
    op.create_index(op.f('ix_compras_created_by'), 'compras', ['created_by'], unique=False)
    op.drop_constraint(None, 'asientos_contables', type_='foreignkey')
    op.drop_index(op.f('ix_asientos_contables_deleted_at'), table_name='asientos_contables')
    op.create_index(op.f('ix_asientos_contables_updated_by'), 'asientos_contables', ['updated_by'], unique=False)
    op.create_index(op.f('ix_asientos_contables_created_by'), 'asientos_contables', ['created_by'], unique=False)
    op.drop_column('asientos_contables', 'deleted_by')
    op.drop_column('asientos_contables', 'deleted_at')
    # ### end Alembic commands ###
