"""initial

Revision ID: 5600c67af29d
Revises: 
Create Date: 2026-02-11 13:28:58.760444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5600c67af29d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_mensual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_anual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_usuarios', sa.Integer(), nullable=False),
    sa.Column('max_productos', sa.Integer(), nullable=False),
    sa.Column('max_facturas_mes', sa.Integer(), nullable=False),
    sa.Column('max_storage_mb', sa.Integer(), nullable=False),
    sa.Column('caracteristicas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('es_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_usuarios >= 1', name='check_max_usuarios_minimo'),
    sa.CheckConstraint('precio_mensual >= 0', name='check_precio_mensual_positivo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('es_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rol IN ('superadmin', 'admin', 'operador', 'contador')", name='check_rol_valido'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('email_contacto', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('url_logo', sa.String(length=500), nullable=True),
    sa.Column('color_primario', sa.String(length=20), nullable=True),
    sa.Column('color_secundario', sa.String(length=20), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio_suscripcion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_fin_suscripcion', sa.DateTime(), nullable=True),
    sa.Column('dias_gracia', sa.Integer(), nullable=True),
    sa.Column('configuracion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('activo', 'suspendido', 'cancelado', 'trial', 'pendiente')", name='check_estado_tenant_valido'),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_index('idx_tenants_estado', 'tenants', ['estado'], unique=False)
    op.create_index('idx_tenants_plan', 'tenants', ['plan_id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('asientos_contables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_asiento', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo_asiento', sa.String(length=50), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('documento_referencia', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("estado IN ('ACTIVO', 'ANULADO')", name='check_estado_asiento_valido'),
    sa.CheckConstraint("tipo_asiento IN ('VENTAS', 'COMPRAS', 'PRODUCCION', 'AJUSTE', 'NOMINA', 'OTRO')", name='check_tipo_asiento_valido'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asientos_tenant_fecha', 'asientos_contables', ['tenant_id', 'fecha'], unique=False)
    op.create_index('idx_asientos_tenant_numero', 'asientos_contables', ['tenant_id', 'numero_asiento'], unique=True)
    op.create_index(op.f('ix_asientos_contables_fecha'), 'asientos_contables', ['fecha'], unique=False)
    op.create_index(op.f('ix_asientos_contables_numero_asiento'), 'asientos_contables', ['numero_asiento'], unique=False)
    op.create_index(op.f('ix_asientos_contables_tenant_id'), 'asientos_contables', ['tenant_id'], unique=False)
    op.create_table('cuentas_contables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo_cuenta', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('cuenta_padre_id', sa.UUID(), nullable=True),
    sa.Column('naturaleza', sa.String(length=20), nullable=False),
    sa.Column('acepta_movimiento', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("naturaleza IN ('DEBITO', 'CREDITO')", name='check_naturaleza_valida'),
    sa.CheckConstraint("tipo_cuenta IN ('ACTIVO', 'PASIVO', 'PATRIMONIO', 'INGRESO', 'EGRESO', 'COSTOS')", name='check_tipo_cuenta_valido'),
    sa.CheckConstraint('nivel >= 1 AND nivel <= 6', name='check_nivel_valido'),
    sa.ForeignKeyConstraint(['cuenta_padre_id'], ['cuentas_contables.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cuentas_contables_tenant_codigo', 'cuentas_contables', ['tenant_id', 'codigo'], unique=True)
    op.create_index(op.f('ix_cuentas_contables_codigo'), 'cuentas_contables', ['codigo'], unique=False)
    op.create_index(op.f('ix_cuentas_contables_tenant_id'), 'cuentas_contables', ['tenant_id'], unique=False)
    op.create_table('medios_pago',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('requiere_referencia', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("tipo IN ('EFECTIVO', 'TRANSFERENCIA', 'CHEQUE', 'TARJETA_CREDITO', 'TARJETA_DEBITO', 'OTRO')", name='check_tipo_medio_pago_valido'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medios_pago_tenant_nombre', 'medios_pago', ['tenant_id', 'nombre'], unique=True)
    op.create_index(op.f('ix_medios_pago_tenant_id'), 'medios_pago', ['tenant_id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=False),
    sa.Column('codigo_barras', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('maneja_inventario', sa.Boolean(), nullable=False),
    sa.Column('porcentaje_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tipo_iva', sa.String(length=20), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('stock_maximo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("categoria IN ('Insumo', 'Producto_Propio', 'Producto_Tercero', 'Servicio')", name='check_categoria_valida'),
    sa.CheckConstraint("tipo_iva IN ('Excluido', 'Exento', 'Gravado')", name='check_tipo_iva_valido'),
    sa.CheckConstraint("unidad_medida IN ('UNIDAD', 'KILOGRAMO', 'GRAMO', 'LITRO', 'METRO', 'CAJA', 'SET')", name='check_unidad_medida_valida'),
    sa.CheckConstraint('precio_venta >= 0', name='check_precio_venta_positivo'),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_productos_tenant_barras', 'productos', ['tenant_id', 'codigo_barras'], unique=True, postgresql_where=sa.text('codigo_barras IS NOT NULL'))
    op.create_index('idx_productos_tenant_codigo', 'productos', ['tenant_id', 'codigo_interno'], unique=True)
    op.create_index(op.f('ix_productos_codigo_barras'), 'productos', ['codigo_barras'], unique=False)
    op.create_index(op.f('ix_productos_codigo_interno'), 'productos', ['codigo_interno'], unique=False)
    op.create_index(op.f('ix_productos_deleted_at'), 'productos', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_productos_tenant_id'), 'productos', ['tenant_id'], unique=False)
    op.create_table('secuencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('prefijo', sa.String(length=20), nullable=False),
    sa.Column('siguiente_numero', sa.Integer(), nullable=False),
    sa.Column('longitud_numero', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('longitud_numero >= 1 AND longitud_numero <= 10', name='check_longitud_valida'),
    sa.CheckConstraint('siguiente_numero >= 1', name='check_siguiente_numero_positivo'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_secuencias_tenant_nombre', 'secuencias', ['tenant_id', 'nombre'], unique=True)
    op.create_index(op.f('ix_secuencias_nombre'), 'secuencias', ['nombre'], unique=False)
    op.create_index(op.f('ix_secuencias_tenant_id'), 'secuencias', ['tenant_id'], unique=False)
    op.create_table('suscripciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('periodo_inicio', sa.DateTime(), nullable=False),
    sa.Column('periodo_fin', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('proveedor_pago', sa.String(length=50), nullable=True),
    sa.Column('id_suscripcion_externa', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('activo', 'suspendido', 'cancelado', 'expirado', 'trial')", name='check_estado_suscripcion_valido'),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suscripciones_tenant_estado', 'suscripciones', ['tenant_id', 'estado'], unique=False)
    op.create_index(op.f('ix_suscripciones_tenant_id'), 'suscripciones', ['tenant_id'], unique=False)
    op.create_table('terceros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=20), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo_tercero', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("tipo_documento IN ('CC', 'NIT', 'CE', 'PAS', 'TI')", name='check_tipo_documento_valido'),
    sa.CheckConstraint("tipo_tercero IN ('CLIENTE', 'PROVEEDOR', 'AMBOS')", name='check_tipo_tercero_valido'),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_terceros_tenant_documento', 'terceros', ['tenant_id', 'numero_documento'], unique=True)
    op.create_index(op.f('ix_terceros_deleted_at'), 'terceros', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_terceros_numero_documento'), 'terceros', ['numero_documento'], unique=False)
    op.create_index(op.f('ix_terceros_tenant_id'), 'terceros', ['tenant_id'], unique=False)
    op.create_table('usuarios_tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('es_default', sa.Boolean(), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rol IN ('superadmin', 'admin', 'operador', 'contador', 'vendedor', 'readonly')", name='check_rol_tenant_valido'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'tenant_id', name='uq_usuario_tenant')
    )
    op.create_index('idx_usuarios_tenants_tenant', 'usuarios_tenants', ['tenant_id'], unique=False)
    op.create_index('idx_usuarios_tenants_usuario', 'usuarios_tenants', ['usuario_id'], unique=False)
    op.create_table('cartera',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_cartera', sa.String(length=20), nullable=False),
    sa.Column('documento_referencia', sa.String(length=100), nullable=False),
    sa.Column('tercero_id', sa.UUID(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("estado IN ('PENDIENTE', 'PARCIAL', 'PAGADA', 'VENCIDA', 'ANULADA')", name='check_estado_cartera_valido'),
    sa.CheckConstraint("tipo_cartera IN ('COBRAR', 'PAGAR')", name='check_tipo_cartera_valido'),
    sa.CheckConstraint('saldo_pendiente >= 0', name='check_saldo_positivo'),
    sa.CheckConstraint('valor_total >= 0', name='check_valor_total_positivo'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cartera_tenant_documento', 'cartera', ['tenant_id', 'documento_referencia'], unique=False)
    op.create_index('idx_cartera_tenant_tercero', 'cartera', ['tenant_id', 'tercero_id'], unique=False)
    op.create_index('idx_cartera_tenant_tipo_estado', 'cartera', ['tenant_id', 'tipo_cartera', 'estado'], unique=False)
    op.create_index(op.f('ix_cartera_documento_referencia'), 'cartera', ['documento_referencia'], unique=False)
    op.create_index(op.f('ix_cartera_fecha_emision'), 'cartera', ['fecha_emision'], unique=False)
    op.create_index(op.f('ix_cartera_fecha_vencimiento'), 'cartera', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_cartera_tenant_id'), 'cartera', ['tenant_id'], unique=False)
    op.create_table('compras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_compra', sa.String(length=50), nullable=False),
    sa.Column('tercero_id', sa.UUID(), nullable=False),
    sa.Column('fecha_compra', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'RECIBIDA', 'ANULADA', name='estadocompra'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compras_tenant_fecha_estado', 'compras', ['tenant_id', 'fecha_compra', 'estado'], unique=False)
    op.create_index('idx_compras_tenant_numero', 'compras', ['tenant_id', 'numero_compra'], unique=True)
    op.create_index('idx_compras_tenant_tercero', 'compras', ['tenant_id', 'tercero_id'], unique=False)
    op.create_index(op.f('ix_compras_deleted_at'), 'compras', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_compras_fecha_compra'), 'compras', ['fecha_compra'], unique=False)
    op.create_index(op.f('ix_compras_numero_compra'), 'compras', ['numero_compra'], unique=False)
    op.create_index(op.f('ix_compras_tenant_id'), 'compras', ['tenant_id'], unique=False)
    op.create_table('configuracion_contable',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concepto', sa.String(length=100), nullable=False),
    sa.Column('cuenta_debito_id', sa.UUID(), nullable=True),
    sa.Column('cuenta_credito_id', sa.UUID(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_credito_id'], ['cuentas_contables.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cuenta_debito_id'], ['cuentas_contables.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_contable_tenant_concepto', 'configuracion_contable', ['tenant_id', 'concepto'], unique=True)
    op.create_index(op.f('ix_configuracion_contable_concepto'), 'configuracion_contable', ['concepto'], unique=False)
    op.create_index(op.f('ix_configuracion_contable_tenant_id'), 'configuracion_contable', ['tenant_id'], unique=False)
    op.create_table('cotizaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_cotizacion', sa.String(length=50), nullable=False),
    sa.Column('tercero_id', sa.UUID(), nullable=False),
    sa.Column('fecha_cotizacion', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("estado IN ('VIGENTE', 'VENCIDA', 'ACEPTADA', 'RECHAZADA')", name='check_estado_cotizacion_valido'),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cotizaciones_tenant_fecha', 'cotizaciones', ['tenant_id', 'fecha_cotizacion'], unique=False)
    op.create_index('idx_cotizaciones_tenant_numero', 'cotizaciones', ['tenant_id', 'numero_cotizacion'], unique=True)
    op.create_index('idx_cotizaciones_tenant_tercero', 'cotizaciones', ['tenant_id', 'tercero_id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_deleted_at'), 'cotizaciones', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cotizaciones_fecha_cotizacion'), 'cotizaciones', ['fecha_cotizacion'], unique=False)
    op.create_index(op.f('ix_cotizaciones_numero_cotizacion'), 'cotizaciones', ['numero_cotizacion'], unique=False)
    op.create_index(op.f('ix_cotizaciones_tenant_id'), 'cotizaciones', ['tenant_id'], unique=False)
    op.create_table('detalles_asiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asiento_id', sa.UUID(), nullable=False),
    sa.Column('cuenta_id', sa.UUID(), nullable=False),
    sa.Column('debito', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credito', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(debito > 0 AND credito = 0) OR (debito = 0 AND credito > 0)', name='check_debito_o_credito'),
    sa.CheckConstraint('credito >= 0', name='check_credito_positivo'),
    sa.CheckConstraint('debito >= 0', name='check_debito_positivo'),
    sa.ForeignKeyConstraint(['asiento_id'], ['asientos_contables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_contables.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detalles_asiento_tenant_asiento', 'detalles_asiento', ['tenant_id', 'asiento_id'], unique=False)
    op.create_index('idx_detalles_asiento_tenant_cuenta', 'detalles_asiento', ['tenant_id', 'cuenta_id'], unique=False)
    op.create_index(op.f('ix_detalles_asiento_tenant_id'), 'detalles_asiento', ['tenant_id'], unique=False)
    op.create_table('historial_pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suscripcion_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('id_transaccion_externa', sa.String(length=200), nullable=True),
    sa.Column('firma_webhook', sa.Text(), nullable=True),
    sa.Column('metadata_pago', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente', 'aprobado', 'rechazado', 'reembolsado')", name='check_estado_pago_valido'),
    sa.CheckConstraint('monto > 0', name='check_monto_pago_positivo'),
    sa.ForeignKeyConstraint(['suscripcion_id'], ['suscripciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_transaccion_externa')
    )
    op.create_index(op.f('ix_historial_pagos_suscripcion_id'), 'historial_pagos', ['suscripcion_id'], unique=False)
    op.create_table('inventarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad_disponible', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('costo_promedio_ponderado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('cantidad_disponible >= 0', name='check_cantidad_positiva'),
    sa.CheckConstraint('costo_promedio_ponderado >= 0', name='check_costo_positivo'),
    sa.CheckConstraint('valor_total >= 0', name='check_valor_positivo'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventarios_tenant_producto', 'inventarios', ['tenant_id', 'producto_id'], unique=True)
    op.create_index(op.f('ix_inventarios_producto_id'), 'inventarios', ['producto_id'], unique=False)
    op.create_index(op.f('ix_inventarios_tenant_id'), 'inventarios', ['tenant_id'], unique=False)
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('ENTRADA', 'SALIDA', 'AJUSTE', 'PRODUCCION', 'DEVOLUCION', name='tipomovimiento'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('documento_referencia', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_movimiento', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('cantidad != 0', name='check_cantidad_no_cero'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movimientos_tenant_producto_fecha', 'movimientos_inventario', ['tenant_id', 'producto_id', 'fecha_movimiento'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_tenant_id'), 'movimientos_inventario', ['tenant_id'], unique=False)
    op.create_table('ordenes_produccion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_orden', sa.String(length=50), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad_producir', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin_estimada', sa.Date(), nullable=True),
    sa.Column('fecha_fin_real', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROCESO', 'COMPLETADA', 'ANULADA', name='estadoordenproduccion'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('cantidad_producir > 0', name='check_cantidad_producir_positiva'),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ordenes_tenant_fecha_estado', 'ordenes_produccion', ['tenant_id', 'fecha_inicio', 'estado'], unique=False)
    op.create_index('idx_ordenes_tenant_numero', 'ordenes_produccion', ['tenant_id', 'numero_orden'], unique=True)
    op.create_index('idx_ordenes_tenant_producto', 'ordenes_produccion', ['tenant_id', 'producto_id'], unique=False)
    op.create_index(op.f('ix_ordenes_produccion_deleted_at'), 'ordenes_produccion', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ordenes_produccion_numero_orden'), 'ordenes_produccion', ['numero_orden'], unique=False)
    op.create_index(op.f('ix_ordenes_produccion_tenant_id'), 'ordenes_produccion', ['tenant_id'], unique=False)
    op.create_table('recetas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('producto_resultado_id', sa.UUID(), nullable=False),
    sa.Column('cantidad_resultado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_mano_obra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tiempo_produccion_minutos', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('cantidad_resultado > 0', name='check_receta_cantidad_positiva'),
    sa.CheckConstraint('costo_mano_obra >= 0', name='check_receta_mano_obra_positiva'),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producto_resultado_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recetas_tenant_nombre', 'recetas', ['tenant_id', 'nombre'], unique=True)
    op.create_index('idx_recetas_tenant_producto', 'recetas', ['tenant_id', 'producto_resultado_id'], unique=False)
    op.create_index(op.f('ix_recetas_deleted_at'), 'recetas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_recetas_producto_resultado_id'), 'recetas', ['producto_resultado_id'], unique=False)
    op.create_index(op.f('ix_recetas_tenant_id'), 'recetas', ['tenant_id'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_venta', sa.String(length=50), nullable=False),
    sa.Column('tercero_id', sa.UUID(), nullable=False),
    sa.Column('fecha_venta', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADA', 'ANULADA', 'FACTURADA', name='estadoventa'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ventas_tenant_fecha_estado', 'ventas', ['tenant_id', 'fecha_venta', 'estado'], unique=False)
    op.create_index('idx_ventas_tenant_numero', 'ventas', ['tenant_id', 'numero_venta'], unique=True)
    op.create_index('idx_ventas_tenant_tercero', 'ventas', ['tenant_id', 'tercero_id'], unique=False)
    op.create_index(op.f('ix_ventas_deleted_at'), 'ventas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ventas_fecha_venta'), 'ventas', ['fecha_venta'], unique=False)
    op.create_index(op.f('ix_ventas_numero_venta'), 'ventas', ['numero_venta'], unique=False)
    op.create_index(op.f('ix_ventas_tenant_id'), 'ventas', ['tenant_id'], unique=False)
    op.create_table('compras_detalle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('compra_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('porcentaje_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='check_compra_cantidad_positiva'),
    sa.CheckConstraint('descuento >= 0', name='check_compra_descuento_positivo'),
    sa.CheckConstraint('precio_unitario >= 0', name='check_compra_precio_positivo'),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compras_detalle_tenant_compra', 'compras_detalle', ['tenant_id', 'compra_id'], unique=False)
    op.create_index('idx_compras_detalle_tenant_producto', 'compras_detalle', ['tenant_id', 'producto_id'], unique=False)
    op.create_index(op.f('ix_compras_detalle_tenant_id'), 'compras_detalle', ['tenant_id'], unique=False)
    op.create_table('cotizaciones_detalle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cotizacion_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('porcentaje_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='check_cotizacion_cantidad_positiva'),
    sa.CheckConstraint('precio_unitario >= 0', name='check_cotizacion_precio_positivo'),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cotizaciones_detalle_tenant_cot', 'cotizaciones_detalle', ['tenant_id', 'cotizacion_id'], unique=False)
    op.create_index('idx_cotizaciones_detalle_tenant_producto', 'cotizaciones_detalle', ['tenant_id', 'producto_id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_detalle_tenant_id'), 'cotizaciones_detalle', ['tenant_id'], unique=False)
    op.create_table('ordenes_produccion_detalle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orden_id', sa.UUID(), nullable=False),
    sa.Column('insumo_id', sa.UUID(), nullable=False),
    sa.Column('cantidad_requerida', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('cantidad_requerida > 0', name='check_cantidad_requerida_positiva'),
    sa.CheckConstraint('costo_unitario >= 0', name='check_costo_unitario_positivo'),
    sa.ForeignKeyConstraint(['insumo_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_produccion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ordenes_detalle_tenant_insumo', 'ordenes_produccion_detalle', ['tenant_id', 'insumo_id'], unique=False)
    op.create_index('idx_ordenes_detalle_tenant_orden', 'ordenes_produccion_detalle', ['tenant_id', 'orden_id'], unique=False)
    op.create_index(op.f('ix_ordenes_produccion_detalle_tenant_id'), 'ordenes_produccion_detalle', ['tenant_id'], unique=False)
    op.create_table('pagos_cartera',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cartera_id', sa.UUID(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('medio_pago_id', sa.UUID(), nullable=False),
    sa.Column('numero_referencia', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('valor_pago > 0', name='check_valor_pago_positivo'),
    sa.ForeignKeyConstraint(['cartera_id'], ['cartera.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medio_pago_id'], ['medios_pago.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pagos_cartera_tenant_cartera', 'pagos_cartera', ['tenant_id', 'cartera_id'], unique=False)
    op.create_index('idx_pagos_cartera_tenant_fecha', 'pagos_cartera', ['tenant_id', 'fecha_pago'], unique=False)
    op.create_index(op.f('ix_pagos_cartera_fecha_pago'), 'pagos_cartera', ['fecha_pago'], unique=False)
    op.create_index(op.f('ix_pagos_cartera_tenant_id'), 'pagos_cartera', ['tenant_id'], unique=False)
    op.create_table('recetas_ingredientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receta_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.String(length=200), nullable=True),
    sa.CheckConstraint("unidad IN ('UNIDAD', 'GRAMO', 'KILOGRAMO', 'MILILITRO', 'LITRO', 'METRO', 'CENTIMETRO')", name='check_ingrediente_unidad_valida'),
    sa.CheckConstraint('cantidad > 0', name='check_ingrediente_cantidad_positiva'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ingredientes_receta_producto', 'recetas_ingredientes', ['receta_id', 'producto_id'], unique=True)
    op.create_index(op.f('ix_recetas_ingredientes_producto_id'), 'recetas_ingredientes', ['producto_id'], unique=False)
    op.create_index(op.f('ix_recetas_ingredientes_receta_id'), 'recetas_ingredientes', ['receta_id'], unique=False)
    op.create_table('ventas_detalle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venta_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('porcentaje_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='check_venta_cantidad_positiva'),
    sa.CheckConstraint('descuento >= 0', name='check_venta_descuento_positivo'),
    sa.CheckConstraint('precio_unitario >= 0', name='check_venta_precio_positivo'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ventas_detalle_tenant_producto', 'ventas_detalle', ['tenant_id', 'producto_id'], unique=False)
    op.create_index('idx_ventas_detalle_tenant_venta', 'ventas_detalle', ['tenant_id', 'venta_id'], unique=False)
    op.create_index(op.f('ix_ventas_detalle_tenant_id'), 'ventas_detalle', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_detalle_tenant_id'), table_name='ventas_detalle')
    op.drop_index('idx_ventas_detalle_tenant_venta', table_name='ventas_detalle')
    op.drop_index('idx_ventas_detalle_tenant_producto', table_name='ventas_detalle')
    op.drop_table('ventas_detalle')
    op.drop_index(op.f('ix_recetas_ingredientes_receta_id'), table_name='recetas_ingredientes')
    op.drop_index(op.f('ix_recetas_ingredientes_producto_id'), table_name='recetas_ingredientes')
    op.drop_index('idx_ingredientes_receta_producto', table_name='recetas_ingredientes')
    op.drop_table('recetas_ingredientes')
    op.drop_index(op.f('ix_pagos_cartera_tenant_id'), table_name='pagos_cartera')
    op.drop_index(op.f('ix_pagos_cartera_fecha_pago'), table_name='pagos_cartera')
    op.drop_index('idx_pagos_cartera_tenant_fecha', table_name='pagos_cartera')
    op.drop_index('idx_pagos_cartera_tenant_cartera', table_name='pagos_cartera')
    op.drop_table('pagos_cartera')
    op.drop_index(op.f('ix_ordenes_produccion_detalle_tenant_id'), table_name='ordenes_produccion_detalle')
    op.drop_index('idx_ordenes_detalle_tenant_orden', table_name='ordenes_produccion_detalle')
    op.drop_index('idx_ordenes_detalle_tenant_insumo', table_name='ordenes_produccion_detalle')
    op.drop_table('ordenes_produccion_detalle')
    op.drop_index(op.f('ix_cotizaciones_detalle_tenant_id'), table_name='cotizaciones_detalle')
    op.drop_index('idx_cotizaciones_detalle_tenant_producto', table_name='cotizaciones_detalle')
    op.drop_index('idx_cotizaciones_detalle_tenant_cot', table_name='cotizaciones_detalle')
    op.drop_table('cotizaciones_detalle')
    op.drop_index(op.f('ix_compras_detalle_tenant_id'), table_name='compras_detalle')
    op.drop_index('idx_compras_detalle_tenant_producto', table_name='compras_detalle')
    op.drop_index('idx_compras_detalle_tenant_compra', table_name='compras_detalle')
    op.drop_table('compras_detalle')
    op.drop_index(op.f('ix_ventas_tenant_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_numero_venta'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_fecha_venta'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_deleted_at'), table_name='ventas')
    op.drop_index('idx_ventas_tenant_tercero', table_name='ventas')
    op.drop_index('idx_ventas_tenant_numero', table_name='ventas')
    op.drop_index('idx_ventas_tenant_fecha_estado', table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_recetas_tenant_id'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_producto_resultado_id'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_deleted_at'), table_name='recetas')
    op.drop_index('idx_recetas_tenant_producto', table_name='recetas')
    op.drop_index('idx_recetas_tenant_nombre', table_name='recetas')
    op.drop_table('recetas')
    op.drop_index(op.f('ix_ordenes_produccion_tenant_id'), table_name='ordenes_produccion')
    op.drop_index(op.f('ix_ordenes_produccion_numero_orden'), table_name='ordenes_produccion')
    op.drop_index(op.f('ix_ordenes_produccion_deleted_at'), table_name='ordenes_produccion')
    op.drop_index('idx_ordenes_tenant_producto', table_name='ordenes_produccion')
    op.drop_index('idx_ordenes_tenant_numero', table_name='ordenes_produccion')
    op.drop_index('idx_ordenes_tenant_fecha_estado', table_name='ordenes_produccion')
    op.drop_table('ordenes_produccion')
    op.drop_index(op.f('ix_movimientos_inventario_tenant_id'), table_name='movimientos_inventario')
    op.drop_index('idx_movimientos_tenant_producto_fecha', table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_index(op.f('ix_inventarios_tenant_id'), table_name='inventarios')
    op.drop_index(op.f('ix_inventarios_producto_id'), table_name='inventarios')
    op.drop_index('idx_inventarios_tenant_producto', table_name='inventarios')
    op.drop_table('inventarios')
    op.drop_index(op.f('ix_historial_pagos_suscripcion_id'), table_name='historial_pagos')
    op.drop_table('historial_pagos')
    op.drop_index(op.f('ix_detalles_asiento_tenant_id'), table_name='detalles_asiento')
    op.drop_index('idx_detalles_asiento_tenant_cuenta', table_name='detalles_asiento')
    op.drop_index('idx_detalles_asiento_tenant_asiento', table_name='detalles_asiento')
    op.drop_table('detalles_asiento')
    op.drop_index(op.f('ix_cotizaciones_tenant_id'), table_name='cotizaciones')
    op.drop_index(op.f('ix_cotizaciones_numero_cotizacion'), table_name='cotizaciones')
    op.drop_index(op.f('ix_cotizaciones_fecha_cotizacion'), table_name='cotizaciones')
    op.drop_index(op.f('ix_cotizaciones_deleted_at'), table_name='cotizaciones')
    op.drop_index('idx_cotizaciones_tenant_tercero', table_name='cotizaciones')
    op.drop_index('idx_cotizaciones_tenant_numero', table_name='cotizaciones')
    op.drop_index('idx_cotizaciones_tenant_fecha', table_name='cotizaciones')
    op.drop_table('cotizaciones')
    op.drop_index(op.f('ix_configuracion_contable_tenant_id'), table_name='configuracion_contable')
    op.drop_index(op.f('ix_configuracion_contable_concepto'), table_name='configuracion_contable')
    op.drop_index('idx_config_contable_tenant_concepto', table_name='configuracion_contable')
    op.drop_table('configuracion_contable')
    op.drop_index(op.f('ix_compras_tenant_id'), table_name='compras')
    op.drop_index(op.f('ix_compras_numero_compra'), table_name='compras')
    op.drop_index(op.f('ix_compras_fecha_compra'), table_name='compras')
    op.drop_index(op.f('ix_compras_deleted_at'), table_name='compras')
    op.drop_index('idx_compras_tenant_tercero', table_name='compras')
    op.drop_index('idx_compras_tenant_numero', table_name='compras')
    op.drop_index('idx_compras_tenant_fecha_estado', table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_cartera_tenant_id'), table_name='cartera')
    op.drop_index(op.f('ix_cartera_fecha_vencimiento'), table_name='cartera')
    op.drop_index(op.f('ix_cartera_fecha_emision'), table_name='cartera')
    op.drop_index(op.f('ix_cartera_documento_referencia'), table_name='cartera')
    op.drop_index('idx_cartera_tenant_tipo_estado', table_name='cartera')
    op.drop_index('idx_cartera_tenant_tercero', table_name='cartera')
    op.drop_index('idx_cartera_tenant_documento', table_name='cartera')
    op.drop_table('cartera')
    op.drop_index('idx_usuarios_tenants_usuario', table_name='usuarios_tenants')
    op.drop_index('idx_usuarios_tenants_tenant', table_name='usuarios_tenants')
    op.drop_table('usuarios_tenants')
    op.drop_index(op.f('ix_terceros_tenant_id'), table_name='terceros')
    op.drop_index(op.f('ix_terceros_numero_documento'), table_name='terceros')
    op.drop_index(op.f('ix_terceros_deleted_at'), table_name='terceros')
    op.drop_index('idx_terceros_tenant_documento', table_name='terceros')
    op.drop_table('terceros')
    op.drop_index(op.f('ix_suscripciones_tenant_id'), table_name='suscripciones')
    op.drop_index('idx_suscripciones_tenant_estado', table_name='suscripciones')
    op.drop_table('suscripciones')
    op.drop_index(op.f('ix_secuencias_tenant_id'), table_name='secuencias')
    op.drop_index(op.f('ix_secuencias_nombre'), table_name='secuencias')
    op.drop_index('idx_secuencias_tenant_nombre', table_name='secuencias')
    op.drop_table('secuencias')
    op.drop_index(op.f('ix_productos_tenant_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_deleted_at'), table_name='productos')
    op.drop_index(op.f('ix_productos_codigo_interno'), table_name='productos')
    op.drop_index(op.f('ix_productos_codigo_barras'), table_name='productos')
    op.drop_index('idx_productos_tenant_codigo', table_name='productos')
    op.drop_index('idx_productos_tenant_barras', table_name='productos', postgresql_where=sa.text('codigo_barras IS NOT NULL'))
    op.drop_table('productos')
    op.drop_index(op.f('ix_medios_pago_tenant_id'), table_name='medios_pago')
    op.drop_index('idx_medios_pago_tenant_nombre', table_name='medios_pago')
    op.drop_table('medios_pago')
    op.drop_index(op.f('ix_cuentas_contables_tenant_id'), table_name='cuentas_contables')
    op.drop_index(op.f('ix_cuentas_contables_codigo'), table_name='cuentas_contables')
    op.drop_index('idx_cuentas_contables_tenant_codigo', table_name='cuentas_contables')
    op.drop_table('cuentas_contables')
    op.drop_index(op.f('ix_asientos_contables_tenant_id'), table_name='asientos_contables')
    op.drop_index(op.f('ix_asientos_contables_numero_asiento'), table_name='asientos_contables')
    op.drop_index(op.f('ix_asientos_contables_fecha'), table_name='asientos_contables')
    op.drop_index('idx_asientos_tenant_numero', table_name='asientos_contables')
    op.drop_index('idx_asientos_tenant_fecha', table_name='asientos_contables')
    op.drop_table('asientos_contables')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index('idx_tenants_plan', table_name='tenants')
    op.drop_index('idx_tenants_estado', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('planes')
    # ### end Alembic commands ###
