"""add_imagen_s3_key_to_productos

Revision ID: 5694eec66f4b
Revises: 13a81d111ca1
Create Date: 2026-03-06 08:25:14.898760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5694eec66f4b'
down_revision: Union[str, None] = '13a81d111ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('imagen_s3_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'imagen_s3_key')
    # ### end Alembic commands ###
