"""add descuento_global to ventas compras cotizaciones

Revision ID: 5937bd34a1a8
Revises: 27e3081a2522
Create Date: 2026-02-12 16:37:17.434492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5937bd34a1a8'
down_revision: Union[str, None] = '27e3081a2522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compras', sa.Column('descuento_global', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0.00'))
    op.add_column('cotizaciones', sa.Column('descuento_global', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0.00'))
    op.add_column('ventas', sa.Column('descuento_global', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'descuento_global')
    op.drop_column('cotizaciones', 'descuento_global')
    op.drop_column('compras', 'descuento_global')
    # ### end Alembic commands ###
