"""detalles_asiento_audit_mixin

Revision ID: 835b979b6465
Revises: 30bd1c39837f
Create Date: 2026-03-07 02:00:14.816178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835b979b6465'
down_revision: Union[str, None] = '30bd1c39837f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_asiento', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('detalles_asiento', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('detalles_asiento', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('detalles_asiento', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('detalles_asiento', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('detalles_asiento', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_detalles_asiento_deleted_at'), 'detalles_asiento', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'detalles_asiento', 'usuarios', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'detalles_asiento', 'usuarios', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'detalles_asiento', 'usuarios', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalles_asiento', type_='foreignkey')
    op.drop_constraint(None, 'detalles_asiento', type_='foreignkey')
    op.drop_constraint(None, 'detalles_asiento', type_='foreignkey')
    op.drop_index(op.f('ix_detalles_asiento_deleted_at'), table_name='detalles_asiento')
    op.drop_column('detalles_asiento', 'updated_by')
    op.drop_column('detalles_asiento', 'created_by')
    op.drop_column('detalles_asiento', 'updated_at')
    op.drop_column('detalles_asiento', 'created_at')
    op.drop_column('detalles_asiento', 'deleted_by')
    op.drop_column('detalles_asiento', 'deleted_at')
    # ### end Alembic commands ###
