"""add CRM fields to terceros

Revision ID: b0955cb14c15
Revises: 5937bd34a1a8
Create Date: 2026-02-12 22:04:29.366881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0955cb14c15'
down_revision: Union[str, None] = '5937bd34a1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terceros', sa.Column('notas', sa.Text(), nullable=True))
    op.add_column('terceros', sa.Column('limite_credito', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=True))
    op.add_column('terceros', sa.Column('plazo_pago_dias', sa.Integer(), server_default='0', nullable=True))
    op.add_column('terceros', sa.Column('persona_contacto', sa.String(length=200), nullable=True))
    op.add_column('terceros', sa.Column('sector_economico', sa.String(length=100), nullable=True))
    op.add_column('terceros', sa.Column('grupo_cliente', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terceros', 'grupo_cliente')
    op.drop_column('terceros', 'sector_economico')
    op.drop_column('terceros', 'persona_contacto')
    op.drop_column('terceros', 'plazo_pago_dias')
    op.drop_column('terceros', 'limite_credito')
    op.drop_column('terceros', 'notas')
    # ### end Alembic commands ###
