"""add_crm_tables

Revision ID: b4c55005691b
Revises: a1b2c3d4e5f6
Create Date: 2026-02-13 12:16:19.852539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c55005691b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_pipelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_default', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('configuracion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_pipeline_tenant_default', 'crm_pipelines', ['tenant_id', 'es_default'], unique=False)
    op.create_index(op.f('ix_crm_pipelines_deleted_at'), 'crm_pipelines', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_crm_pipelines_tenant_id'), 'crm_pipelines', ['tenant_id'], unique=False)
    op.create_table('crm_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('probabilidad', sa.Integer(), nullable=True),
    sa.Column('requiere_motivo_perdida', sa.Boolean(), nullable=True),
    sa.Column('dias_estancamiento_alerta', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('probabilidad >= 0 AND probabilidad <= 100', name='check_crm_stage_probabilidad'),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['crm_pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_stage_pipeline_orden', 'crm_stages', ['pipeline_id', 'orden'], unique=False)
    op.create_index(op.f('ix_crm_stages_deleted_at'), 'crm_stages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_crm_stages_pipeline_id'), 'crm_stages', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_crm_stages_tenant_id'), 'crm_stages', ['tenant_id'], unique=False)
    op.create_table('crm_deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tercero_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('valor_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('fecha_cierre_estimada', sa.Date(), nullable=True),
    sa.Column('estado_cierre', sa.Enum('ABIERTO', 'GANADO', 'PERDIDO', 'ABANDONADO', name='estadodeal'), nullable=False),
    sa.Column('motivo_perdida', sa.Text(), nullable=True),
    sa.Column('origen', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultimo_contacto', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['crm_pipelines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['crm_stages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_deals_tenant_stage', 'crm_deals', ['tenant_id', 'stage_id'], unique=False)
    op.create_index('idx_crm_deals_tenant_usuario', 'crm_deals', ['tenant_id', 'usuario_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_deleted_at'), 'crm_deals', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_crm_deals_stage_id'), 'crm_deals', ['stage_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_tenant_id'), 'crm_deals', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_tercero_id'), 'crm_deals', ['tercero_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_usuario_id'), 'crm_deals', ['usuario_id'], unique=False)
    op.create_table('crm_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('NOTA', 'LLAMADA', 'EMAIL', 'REUNION', 'WHATSAPP', 'TAREA', name='tipoactividadcrm'), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha_actividad', sa.DateTime(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('es_automatica', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_activities_tenant_deal_fecha', 'crm_activities', ['tenant_id', 'deal_id', 'fecha_actividad'], unique=False)
    op.create_index(op.f('ix_crm_activities_deal_id'), 'crm_activities', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_deleted_at'), 'crm_activities', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_crm_activities_tenant_id'), 'crm_activities', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_crm_activities_tenant_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_deleted_at'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_deal_id'), table_name='crm_activities')
    op.drop_index('idx_crm_activities_tenant_deal_fecha', table_name='crm_activities')
    op.drop_table('crm_activities')
    op.drop_index(op.f('ix_crm_deals_usuario_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_tercero_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_tenant_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_stage_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_deleted_at'), table_name='crm_deals')
    op.drop_index('idx_crm_deals_tenant_usuario', table_name='crm_deals')
    op.drop_index('idx_crm_deals_tenant_stage', table_name='crm_deals')
    op.drop_table('crm_deals')
    op.drop_index(op.f('ix_crm_stages_tenant_id'), table_name='crm_stages')
    op.drop_index(op.f('ix_crm_stages_pipeline_id'), table_name='crm_stages')
    op.drop_index(op.f('ix_crm_stages_deleted_at'), table_name='crm_stages')
    op.drop_index('idx_crm_stage_pipeline_orden', table_name='crm_stages')
    op.drop_table('crm_stages')
    op.drop_index(op.f('ix_crm_pipelines_tenant_id'), table_name='crm_pipelines')
    op.drop_index(op.f('ix_crm_pipelines_deleted_at'), table_name='crm_pipelines')
    op.drop_index('idx_crm_pipeline_tenant_default', table_name='crm_pipelines')
    op.drop_table('crm_pipelines')
    # ### end Alembic commands ###
