"""add_tickets_pqrs

Revision ID: cbb160c37bbc
Revises: 23fa462778a8
Create Date: 2026-02-24 11:16:05.353012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbb160c37bbc'
down_revision: Union[str, None] = '23fa462778a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets_pqrs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('PETICION', 'QUEJA', 'RECLAMO', 'SUGERENCIA', 'SOPORTE', name='tipopqrs'), nullable=False),
    sa.Column('asunto', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'EN_PROCESO', 'RESUELTO', 'CERRADO', name='estadoticket'), nullable=False),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'CRITICA', name='prioridadticket'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('respuestas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tickets_pqrs_tenant_estado', 'tickets_pqrs', ['tenant_id', 'estado'], unique=False)
    op.create_index('idx_tickets_pqrs_tenant_tipo', 'tickets_pqrs', ['tenant_id', 'tipo'], unique=False)
    op.create_index('idx_tickets_pqrs_tenant_usuario', 'tickets_pqrs', ['tenant_id', 'usuario_id'], unique=False)
    op.create_index(op.f('ix_tickets_pqrs_deleted_at'), 'tickets_pqrs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tickets_pqrs_tenant_id'), 'tickets_pqrs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tickets_pqrs_usuario_id'), 'tickets_pqrs', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_pqrs_usuario_id'), table_name='tickets_pqrs')
    op.drop_index(op.f('ix_tickets_pqrs_tenant_id'), table_name='tickets_pqrs')
    op.drop_index(op.f('ix_tickets_pqrs_deleted_at'), table_name='tickets_pqrs')
    op.drop_index('idx_tickets_pqrs_tenant_usuario', table_name='tickets_pqrs')
    op.drop_index('idx_tickets_pqrs_tenant_tipo', table_name='tickets_pqrs')
    op.drop_index('idx_tickets_pqrs_tenant_estado', table_name='tickets_pqrs')
    op.drop_table('tickets_pqrs')
    # ### end Alembic commands ###
