"""add_costo_unitario_to_ventas_detalle

Revision ID: de736ea93ccf
Revises: 5694eec66f4b
Create Date: 2026-03-06 22:54:18.364592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de736ea93ccf'
down_revision: Union[str, None] = '5694eec66f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas_detalle', sa.Column('costo_unitario', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas_detalle', 'costo_unitario')
    # ### end Alembic commands ###
