#!/usr/bin/env python3
"""
Claude AI Security PR Reviewer
Used by .github/workflows/ai-review.yml

Reads the PR diff from pr_diff.txt and asks Claude to review it for:
1. Missing tenant_id validation in DB queries
2. Hardcoded secrets/credentials
3. OWASP Top 10 vulnerability patterns
4. Authentication/authorization issues

Posts the review as a PR comment and sets the output severity.
Exits with code 1 if CRITICAL findings are detected (blocks merge).

Required env vars:
  ANTHROPIC_API_KEY  — Claude API key
  GITHUB_TOKEN       — GitHub token (for posting comments)
  PR_NUMBER          — Pull request number
  PR_TITLE           — Pull request title
  REPO               — GitHub repository (owner/name)
"""
import os
import sys
import json

try:
    import anthropic
    import httpx
except ImportError:
    print("ERROR: Missing dependencies. Run: pip install anthropic httpx")
    sys.exit(1)

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
PR_NUMBER = os.environ.get("PR_NUMBER", "")
PR_TITLE = os.environ.get("PR_TITLE", "")
REPO = os.environ.get("REPO", "")

# GitHub Actions output file
GITHUB_OUTPUT = os.environ.get("GITHUB_OUTPUT", "")

if not ANTHROPIC_API_KEY:
    print("WARNING: ANTHROPIC_API_KEY not set. Skipping AI review.")
    sys.exit(0)


def read_diff() -> str:
    """Read the PR diff from file generated by the workflow."""
    diff_path = "pr_diff.txt"
    if not os.path.exists(diff_path):
        print(f"ERROR: {diff_path} not found. Did the 'Get PR diff' step run?")
        sys.exit(1)

    with open(diff_path, "r", encoding="utf-8", errors="replace") as f:
        diff = f.read()

    # Truncate if too large (Claude has context limits)
    max_chars = 60_000
    if len(diff) > max_chars:
        diff = diff[:max_chars] + "\n\n[... diff truncated due to size ...]"

    return diff


def run_security_review(diff: str) -> dict:
    """Call Claude API for security review of the diff."""
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    system_prompt = """You are a senior application security engineer reviewing a pull request diff for a
multitenant ERP system (FastAPI + PostgreSQL). Your job is to identify ONLY security issues.

FOCUS AREAS:
1. **Tenant Isolation** — Every DB query on tenant data must call set_tenant_context_for_session()
   or include explicit tenant_id filtering. Flag any route that accesses tenant models without it.
2. **Hardcoded Secrets** — Passwords, API keys, tokens, connection strings in code (not env vars).
3. **OWASP Top 10** — SQL injection, XSS, CSRF bypass, broken auth, insecure deserialization,
   IDOR (insecure direct object reference), security misconfiguration.
4. **Authentication** — Missing authentication dependencies on FastAPI routes, JWT issues.
5. **Authorization** — Missing role/permission checks, privilege escalation paths.

SEVERITY LEVELS:
- CRITICAL: Direct exploitation path, data breach risk, auth bypass
- HIGH: Significant risk, requires immediate fix
- MEDIUM: Should be fixed before merge, lower immediate risk
- LOW: Best practice improvement, informational

OUTPUT FORMAT (JSON only, no markdown wrapper):
{
  "severity": "NONE|LOW|MEDIUM|HIGH|CRITICAL",
  "summary": "One-sentence summary",
  "findings": [
    {
      "severity": "CRITICAL|HIGH|MEDIUM|LOW",
      "file": "path/to/file.py",
      "line": "approximate line or range",
      "title": "Short title",
      "description": "What the issue is",
      "recommendation": "How to fix it"
    }
  ],
  "passed": true|false
}

If no security issues found, return: {"severity": "NONE", "summary": "No security issues found.", "findings": [], "passed": true}
Only return JSON. Do not wrap in markdown code blocks."""

    user_message = f"""Please review this pull request diff for security issues.

PR Title: {PR_TITLE}

Diff:
{diff}"""

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2048,
        system=system_prompt,
        messages=[{"role": "user", "content": user_message}],
    )

    content = response.content[0].text.strip()

    # Strip markdown code blocks if model wraps output anyway
    if content.startswith("```"):
        lines = content.split("\n")
        content = "\n".join(lines[1:-1]) if lines[-1] == "```" else "\n".join(lines[1:])

    try:
        return json.loads(content)
    except json.JSONDecodeError:
        print(f"WARNING: Could not parse Claude response as JSON:\n{content}")
        return {
            "severity": "LOW",
            "summary": "AI review completed (parse error — see raw output)",
            "findings": [{"severity": "LOW", "file": "N/A", "line": "N/A",
                          "title": "Review parse error", "description": content,
                          "recommendation": "Check raw output above"}],
            "passed": True,
        }


def format_comment(review: dict) -> str:
    """Format the review result as a GitHub PR comment."""
    severity = review.get("severity", "NONE")
    summary = review.get("summary", "")
    findings = review.get("findings", [])

    severity_emoji = {
        "NONE": "✅",
        "LOW": "ℹ️",
        "MEDIUM": "⚠️",
        "HIGH": "🔶",
        "CRITICAL": "🚨",
    }.get(severity, "🔍")

    lines = [
        f"## {severity_emoji} Claude Security Review — {severity}",
        "",
        f"**Summary:** {summary}",
        "",
    ]

    if not findings:
        lines.append("No security issues detected. ✅")
    else:
        lines.append(f"**{len(findings)} finding(s) detected:**")
        lines.append("")

        for f in findings:
            sev = f.get("severity", "LOW")
            emoji = {"CRITICAL": "🚨", "HIGH": "🔶", "MEDIUM": "⚠️", "LOW": "ℹ️"}.get(sev, "🔍")
            lines.append(f"### {emoji} {sev}: {f.get('title', 'Finding')}")
            lines.append(f"- **File:** `{f.get('file', 'N/A')}` (line {f.get('line', '?')})")
            lines.append(f"- **Issue:** {f.get('description', '')}")
            lines.append(f"- **Fix:** {f.get('recommendation', '')}")
            lines.append("")

    if severity == "CRITICAL":
        lines.append("---")
        lines.append("⛔ **CRITICAL finding detected — merge is blocked until resolved.**")

    lines.append("")
    lines.append("_Reviewed by [Claude Security Reviewer](/.github/workflows/ai-review.yml)_")

    return "\n".join(lines)


def post_pr_comment(comment: str) -> None:
    """Post the review as a comment on the PR."""
    if not GITHUB_TOKEN or not PR_NUMBER or not REPO:
        print("WARNING: Missing GITHUB_TOKEN/PR_NUMBER/REPO — skipping comment post.")
        return

    url = f"https://api.github.com/repos/{REPO}/issues/{PR_NUMBER}/comments"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    resp = httpx.post(url, headers=headers, json={"body": comment})

    if resp.status_code == 201:
        print(f"✅ Review comment posted to PR #{PR_NUMBER}")
    else:
        print(f"WARNING: Failed to post comment ({resp.status_code}): {resp.text}")


def set_output(key: str, value: str) -> None:
    """Write a value to GitHub Actions output."""
    if GITHUB_OUTPUT:
        with open(GITHUB_OUTPUT, "a") as f:
            f.write(f"{key}={value}\n")
    print(f"Output: {key}={value}")


def main():
    print(f"=== Claude AI Security PR Review ===")
    print(f"PR: #{PR_NUMBER} — {PR_TITLE}")
    print(f"Repository: {REPO}")

    diff = read_diff()
    print(f"Diff size: {len(diff)} chars")

    print("Running security analysis with Claude...")
    review = run_security_review(diff)

    severity = review.get("severity", "NONE")
    findings_count = len(review.get("findings", []))
    print(f"Review complete: severity={severity}, findings={findings_count}")

    comment = format_comment(review)
    post_pr_comment(comment)

    set_output("severity", severity)
    set_output("findings_count", str(findings_count))
    set_output("passed", str(review.get("passed", True)).lower())

    # Print summary to Actions log
    print("\n--- Review Summary ---")
    print(comment)

    if severity == "CRITICAL":
        print("\n🚨 CRITICAL finding — exiting with code 1 to block merge.")
        sys.exit(1)

    print("\n✅ Security review complete.")


if __name__ == "__main__":
    main()
